### PR TITLE
Added static method matrixExponential to MatrixUtils.

### PR DESCRIPTION
**Pull request by mgrutten**
As discussed in the Hipparchus forum [matrix exponential](https://forum.orekit.org/t/matrix-exponential/772) thread.

### CODE REVIEW

**Comment by maisonobe** [comment]
I had a first look at it and it seems great to me!
As a new contributor and for a substantial contribution, we would need some paperwork to be legally allowed to publish your work. You can select one of two option: either you intend to contribute other things in the future and then you should fill in a Contributor License Agreement that will cover this and future contributions, or this is a one-shot contribution and then you should fill in a software Grant that will cover only this contribution. You will find links for the forms in the main Hipparchus website : [Licensing and copyright](https://www.hipparchus.org/developers.html#Licensing_and_copyright). As both forms will contain your name and signature, they should of course *not* be put on a public page like this discussion or forum. You should sent it to me directly (a working email is available in the `hipparchus-parent/pom.xml` file)

**Comment by psteitz** [comment]
Looks good to me, though I have not checked against the references.  Where does the data in the test cases come from?

**Comment by mgrutten** [comment]
Thanks!
I'll send through a license form today.

I constructed the exponent matrices in the test cases to explore each of the code branches.  The reference results are calculated using Matlab.

Frankly I didn't know about `DefaultRealMatrixChangingVisitor` until now!  That could make the visitor simple enough for an inline anonymous class?

**Comment by mgrutten** [comment]
Unclose!

**Comment by mgrutten** [comment]
Apologies for the closing and re-opening ... I don't know what I'm doing.

Thanks for looking at the code!  I'll send through a license form today.

I constructed the sample exponent matrices with norms that would explore each of the code branches.  The expected results are calculated using Matlab.

Frankly, I didn't know about `DefaultRealMatrixChangingVisitor` until now.  That could make the visitor simple enough for an inline anonymous class?

**Comment by mgrutten** [comment]
> One small comment: the code could be simplified a little by deriving from DefaultRealMatrixChangingVisitor. Better yet, we deprecate that and add default impls to RealMatrixChangingVisitor now that we require JDK 1.8+

Could I suggest defining `map` and `mapToSelf` methods for `RealMatrix`, similar to `RealVector`?  That way we could write:
`scaledMatrix.mapToSelf(x -> Math.scalb(x, -squaringCount));`
which I find easier to read.

**Comment by maisonobe** [comment]
I agree mapping functions should be nice. It could however be done only on a major release for compatibility reasons (we cannot add new signatures on public interfaces).
I think we will anyway start thinking about Hipparchus 2.0 in the next few months, so it is worth preparing it. Could you open an dedicated issue for adding these new methods?

**Pull request merged**
