### PR TITLE
Issue 215 : Fixed multiple Javadoc errors in code

### PR DESCRIPTION
**Pull request by VincentCucchietti**
Hey everyone,

It took a day but it's finally done, I fixed all javadoc errors preventing the ```mvn javadoc:javadoc````command to build successfully.

I also took this opportunity to replace explicit types T with <> and removed a few unnecessary semicolons.

Lots of code cleanup could be done, but another issue will be better suited for that.

### CODE REVIEW

**Comment by maisonobe** [comment]
There are really many changes there, mixing several different parts (at least javadoc and parameters), which makes the review almost impossible.
The fixes also don't really seem to work in all versions of javadoc. Some seem to introduce new Javadoc errors. At least on my configuration, if I run mvn javadoc:javadoc I get 24 errors and more than 100 warnings (maven stops counting after 100).

With what version of javadoc did you check?

**Comment by maisonobe** [comment]
I checked again, using different versions of javadoc.

With java 1.8 (which is the one Hipparchus wants to be compatible now), there were 0 errors and 0 warnings in the master branch, and there are still 0 errors and 0 warning with your changes.
With Java 17, there are many errors and warnings in both the master branch and your change.

**Comment by MaximeJo** [comment]
Hi @maisonobe,

I tried the same `mvn javadoc:javadoc` with `master` branch and I get multiple Javadoc errors, like dozens for the `core` module and then it fails.
I use Opend JDK 8.0_242, Maven 3.5.2 and the `maven-javadoc-plugin` 3.3.2 (this one comes from the pom).
How did you manage to get 0 error on your side ? I'm baffled.

**Comment by maisonobe** [comment]
I ran this command on a computer running Debian Linux:

```
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 PATH=/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/:$PATH mvn javadoc:javadoc
```

**Comment by maisonobe** [comment]
I gave up on reviewing this, it's too large and mixes different changes.
Could you separate changes according to topics instead of according to changed files?
Could you separate code changes and comments changes?
Could you detail what changes were needed for what version of javadoc?

**Comment by VincentCucchietti** [comment]
I'll try to do as you say whenever I can. 

Thank you for your time Luc.

**Pull request closed without merging**
